### ISSUE TITLE
Exception: A _FakeScrollPositionWithSingleContext was used after being disposed.

### ISSUE THREAD

**Issue by mixable** [optimist-dev/scrolls_to_top#1]
I use `ScrollsToTop` in a screen (let's call it DetailScreen) that is opened using: `Navigator.of(context).push(...);`. The screen is a StatefulWidget where the build method looks like this:

```
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      key: scaffoldKey,
      primary: true,
      body: ScrollsToTop(
        onScrollsToTop: _onScrollsToTop,
        child: Container(
          // ...
```

When closing DetailScreen using `Navigator.of(context).pop();`, the following exception is thrown:

```
======== Exception caught by widgets library =======================================================
The following assertion was thrown while finalizing the widget tree:
A _FakeScrollPositionWithSingleContext was used after being disposed.

Once you have called dispose() on a _FakeScrollPositionWithSingleContext, it can no longer be used.
When the exception was thrown, this was the stack: 
#0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:117:9)
#1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:123:6)
#2      ChangeNotifier.removeListener (package:flutter/src/foundation/change_notifier.dart:195:12)
#3      ScrollController.dispose (package:flutter/src/widgets/scroll_controller.dart:199:16)
#4      _ScrollsToTopState.dispose (package:scrolls_to_top/scrolls_to_top.dart:57:31)
...
====================================================================================================

```

The expected behavior is that DetailScreen (and its subwidgets) is disposed correctly without throwing this exception. DetailScreen disposes all its objects correctly (at least I don't see anything wrong). Is this an issue of `scrolls_to_top` or did I miss something? Any ideas what's going on here?

**Comment by otopba** [comment]
@mixable Hi!
Thank you for this issue.

Could you check on the latest version? I fixed it at https://github.com/optimist-dev/scrolls_to_top/commit/e004f6b80a02811051a0afe563c8f6985e749e52

**Comment by mixable** [comment]
@otopba Thank you for the fast fix. This works as expected!
