### ISSUE TITLE
_primaryScrollController?.detach(_scrollPositionWithSingleContext!) not called

### ISSUE THREAD

**Issue by REKURDennis** [optimist-dev/scrolls_to_top#6]
I think there is a mistake in the dispose() function. I noticed, that unmounted widgets are still being called from "_onScrollsToTop"-method, after they were pushed once and popped again.

In your dispose function you have in line 53 / 54
`_scrollPositionWithSingleContext ??
        _primaryScrollController?.detach(_scrollPositionWithSingleContext!);`

If I see it correctly, the position is only detached, if it were null, which would anyway lead to an error. Therefore it is attached forever.

**Comment by otopba** [comment]
Fixed at version 2.1.0. Thanks!
